version: '3'
services:
  # Vite.js website service
  dev:
    container_name: aussie-everest-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:        
        - NODE_ENV=development
    
    environment:    
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true   

    volumes:
      - ./:/app
      - /app/node_modules

    ports:
      - 5173:5173

    entrypoint: ["npm", "run"]

    command: dev
    